### ISSUE TITLE
"Wrong" shared objects get copied over to site-package. 

### ISSUE THREAD

**Issue by dwhan89** [simonsobs/pixell#54]
* pixell version: 0.5.2
* Python version: python3/3.6-anaconda-4.4
* Operating System: NERSC  

### Description

When I install pixell with `python setup.py install --user` command, it only copy over shared objects with "wrong" name.

### What I Did

First, I install pixell with `python setup.py install` command

```
dwhan89@cori02:~/cori/workspace/pixell3> python setup.py build_ext -i --fcompiler=intelem --compiler=intelem
dwhan89@cori02:~/cori/workspace/pixell3> python setup.py install --user
```
You find both "correct" and "wrongly" named shared object in `./pixell` directory

```
dwhan89@cori02:~/cori/workspace/pixell3/pixell> ls -lrt *.so
-rwxr-x--- 1 dwhan89 dwhan89  133216 Dec  8 12:52 _interpol_32.so
-rwxr-x--- 1 dwhan89 dwhan89  133208 Dec  8 12:52 _interpol_64.so
-rwxr-x--- 1 dwhan89 dwhan89   49568 Dec  8 12:52 _colorize.so
-rwxr-x--- 1 dwhan89 dwhan89   60728 Dec  8 12:52 _array_ops_32.so
-rwxr-x--- 1 dwhan89 dwhan89   60728 Dec  8 12:52 _array_ops_64.so
-rwxr-x--- 1 dwhan89 dwhan89 1181424 Dec  8 12:52 sharp.so
-rwxrwx--- 1 dwhan89 dwhan89 1169032 Mar  7 10:12 sharp.cpython-36m-x86_64-linux-gnu.so
-rwxrwx--- 1 dwhan89 dwhan89  336752 Mar  7 10:56 _interpol_32.cpython-36m-x86_64-linux-gnu.so
-rwxrwx--- 1 dwhan89 dwhan89  333568 Mar  7 10:56 _interpol_64.cpython-36m-x86_64-linux-gnu.so
-rwxrwx--- 1 dwhan89 dwhan89  130288 Mar  7 10:56 _colorize.cpython-36m-x86_64-linux-gnu.so
-rwxrwx--- 1 dwhan89 dwhan89  153928 Mar  7 10:56 _array_ops_32.cpython-36m-x86_64-linux-gnu.so
-rwxrwx--- 1 dwhan89 dwhan89  153912 Mar  7 10:56 _array_ops_64.cpython-36m-x86_64-linux-gnu.so
```
But it copies over only "wrongly" named files to site-package

```
dwhan89@nid00217:~/.local/cori/3.6-anaconda-4.4/lib/python3.6/site-packages/pixell-0.5.2+28.g11cbaf7-py3.6-linux-x86_64.egg/pixell> ls -lrt *.so
-rwxr-xr-x 1 dwhan89 dwhan89  153928 Mar  7 11:41 _array_ops_32.cpython-36m-x86_64-linux-gnu.so
-rwxr-xr-x 1 dwhan89 dwhan89  153912 Mar  7 11:41 _array_ops_64.cpython-36m-x86_64-linux-gnu.so
-rwxr-xr-x 1 dwhan89 dwhan89  130288 Mar  7 11:41 _colorize.cpython-36m-x86_64-linux-gnu.so
-rwxr-xr-x 1 dwhan89 dwhan89  336752 Mar  7 11:41 _interpol_32.cpython-36m-x86_64-linux-gnu.so
-rwxr-xr-x 1 dwhan89 dwhan89  333568 Mar  7 11:41 _interpol_64.cpython-36m-x86_64-linux-gnu.so
-rwxr-xr-x 1 dwhan89 dwhan89 2078768 Mar  7 11:41 sharp.cpython-36m-x86_64-linux-gnu.so
```
So when I try to run some test script, I get `sharp` undefined error

```
dwhan89@nid00217:~/cori/workspace/ps_py3/test> python test_io.py 
Traceback (most recent call last):
  File "test_io.py", line 31, in <module>
    cmb_car=template_car.synfast(clfile)
  File "/global/u2/d/dwhan89/cori/workspace/ps_py3/pspy/so_map.py", line 102, in synfast
    self.data= curvedsky.rand_map(self.data.shape, self.data.wcs, ps)
  File "/global/homes/d/dwhan89/.local/cori/3.6-anaconda-4.4/lib/python3.6/site-packages/pixell-0.5.2+28.g11cbaf7-py3.6-linux-x86_64.egg/pixell/curvedsky.py", line 28, in rand_map
    alm2map(alm, map, spin=spin, oversample=oversample, method=method, direct=direct, verbose=verbose)
  File "/global/homes/d/dwhan89/.local/cori/3.6-anaconda-4.4/lib/python3.6/site-packages/pixell-0.5.2+28.g11cbaf7-py3.6-linux-x86_64.egg/pixell/curvedsky.py", line 92, in alm2map
    alm2map_cyl(alm, map, ainfo=ainfo, spin=spin, deriv=deriv, direct=direct, copy=copy, verbose=verbose)
  File "/global/homes/d/dwhan89/.local/cori/3.6-anaconda-4.4/lib/python3.6/site-packages/pixell-0.5.2+28.g11cbaf7-py3.6-linux-x86_64.egg/pixell/curvedsky.py", line 179, in alm2map_cyl
    alm, ainfo = prepare_alm(alm, ainfo)
  File "/global/homes/d/dwhan89/.local/cori/3.6-anaconda-4.4/lib/python3.6/site-packages/pixell-0.5.2+28.g11cbaf7-py3.6-linux-x86_64.egg/pixell/curvedsky.py", line 467, in prepare_alm
    ainfo = sharp.alm_info(nalm=alm.shape[-1])
NameError: name 'sharp' is not defined
```

I have a workaround by installing it with `pip -e` command. 

```
dwhan89@cori02:~/cori/workspace/pixell3> python setup.py build_ext -i --fcompiler=intelem --compiler=intelem
dwhan89@cori02:~/cori/workspace/pixell3> pip install -e . --user
```
Then the scripts runs fine.
```
dwhan89@nid00217:~/cori/workspace/ps_py3/test> python test_io.py 
/global/u2/d/dwhan89/cori/workspace/pixell3/pixell/enplot.py:629: RuntimeWarning: invalid value encountered in true_divide
  map = ((map.T-crange[0])/(crange[1]-crange[0])).T # .T ensures broadcasting for rgb case
```

**Comment by msyriac** [comment]
@amaurea @mhasself this seems related to OpenMP troubles. Any thoughts?

**Comment by msyriac** [comment]
@dwhan89 are you still able to reproduce this? I don't get files named e.g. "_interpol_32.so" when I run build_ext.

**Comment by mhasself** [comment]
(Aside: I think this is unrelated to OpenMP issues.)

I thought that when one is installing to --user, one should **not** build the extensions with -i (in-place).  You should either:
```
   python setup.py build_ext --fcompiler=intelem
   python setup.py install --user
```
OR
```
   python setup.py build_ext -i --fcompiler=intelem
```
and that is all, because the point of building in-place is that you can import the modules directly from the python source tree.

I would definitely recommend a full clean up and re-test here -- if you've been mixing build_ext -i and install --user, there could be all kinds of stale or misleading library files lying around (in ~/.local, in build/, and in pixell/).

**Comment by dwhan89** [comment]
I can't reproduce this error anymore. Closing the issue.
